### ISSUE TITLE
[ENHANCEMENT] fitslist and summary_report code unification

### ISSUE THREAD

**Issue by WWGolay** [macro-consortium/pyscope#34]
Much of this code is duplicate, unify with private functions. Also, fitslist should return an astropy Table.

**Comment by lilasch** [comment]
I can work on this

**Comment by pgriffin17** [comment]
I'm working on getting fitslist working from command line. Is the goal to still be able to use fitslist as a command line utility? Where does the astropy Table come in here (what should be called to return the astropy Table, or should it return an astropy table as the default to the terminal?)?

**Comment by pgriffin17** [comment]
I am not sure exactly what to look for, if you could point me to the script, that would be helpful.

**Comment by WWGolay** [comment]
Check the verbose flag in rst:
```
verbose : int, {-1, 0, 1}, default=-1
        Verbosity level. 0: no debug messages, 1: debug messages. Default set to -1
        for API use and 0 for CLI use.```
